version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER={echo $MONGO_USER}
      - MONGO_PASSWORD={echo $MONGO_PASSWORD}
      - SESSION_SECRET={echo $SESSION_SECRET}
    command: node index.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME={ echo $MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD={ echo $MONGO_INITDB_ROOT_PASSWORD}